# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    cohort_code_use = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    incidence = FALSE,
    incidence_attrition = FALSE,
    hr_summary = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_cohort_name,
      input$cohort_code_use_codelist_name,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name %in% input$cohort_code_use_cohort_name,
        .data$codelist_name %in% input$cohort_code_use_codelist_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # incidence -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$incidence <- TRUE
  }) |>
    shiny::bindEvent(
      input$incidence_cdm_name,
      input$incidence_outcome_cohort_name,
      input$incidence_ses,
      input$incidence_incidence_start_date,
      input$incidence_analysis_interval,
      input$incidence_analysis_censor_cohort_name,
      input$incidence_analysis_complete_database_intervals,
      input$incidence_analysis_outcome_washout,
      input$incidence_analysis_repeated_events,
      input$incidence_denominator_age_group,
      input$incidence_denominator_days_prior_observation,
      input$incidence_denominator_end_date,
      input$incidence_denominator_requirements_at_entry,
      input$incidence_denominator_sex,
      input$incidence_denominator_start_date,
      input$incidence_denominator_target_cohort_name,
      input$incidence_denominator_time_at_risk,
      input$incidence_standardised_incidence,
      input$incidence_variable_name,
      input$incidence_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$incidence, {
    if (updateButtons$incidence == TRUE) {
      output$update_message_incidence <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_incidence <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_incidence, {
    updateButtons$incidence <- FALSE
  })

  ## get incidence data
  getIncidenceData <- shiny::eventReactive(input$update_incidence, {
    data[["incidence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_cdm_name,
        .data$variable_name %in% input$incidence_variable_name,
        .data$estimate_name %in% input$incidence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$incidence_outcome_cohort_name) |>
      omopgenerics::filterStrata(.data$ses %in% input$incidence_ses) |>
      omopgenerics::filterAdditional(
        .data$incidence_start_date %in% input$incidence_incidence_start_date,
        .data$analysis_interval %in% input$incidence_analysis_interval
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_censor_cohort_name %in% input$incidence_analysis_censor_cohort_name,
        .data$analysis_complete_database_intervals %in% input$incidence_analysis_complete_database_intervals,
        .data$analysis_outcome_washout %in% input$incidence_analysis_outcome_washout,
        .data$analysis_repeated_events %in% input$incidence_analysis_repeated_events,
        .data$denominator_age_group %in% input$incidence_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$incidence_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$incidence_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$incidence_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$incidence_denominator_sex,
        .data$denominator_start_date %in% input$incidence_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$incidence_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$incidence_denominator_time_at_risk,
        .data$standardised_incidence %in% input$incidence_standardised_incidence
      )
  })
  getIncidenceTable <- shiny::reactive({
    res <- getIncidenceData()
    res |>
      IncidencePrevalence::tableIncidence(
        header = input$incidence_table_header,
        groupColumn = input$incidence_table_group_column,
        hide = input$incidence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$incidence_table <- gt::render_gt({
    getIncidenceTable()
  })
  output$incidence_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence.", input$incidence_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceTable(), file)
    }
  )
  getIncidencePlot <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidence(
        x = input$incidence_plot_x,
        facet = input$incidence_plot_facet,
        colour = input$incidence_plot_colour,
        ribbon = input$incidence_plot_ribbon,
        line = input$incidence_plot_line
      )
  })
  output$incidence_plot <- shiny::renderUI({
    x <- getIncidencePlot()
    renderInteractivePlot(x, input$incidence_plot_interactive)
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "plot_incidence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getIncidencePlot(),
        width = as.numeric(input$incidence_plot_width),
        height = as.numeric(input$incidence_plot_height),
        units = input$incidence_plot_units,
        dpi = as.numeric(input$incidence_plot_dpi)
      )
    }
  )
  getIncidencePlotPopulation <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidencePopulation(
        facet = input$incidence_plot_population_facet,
        colour = input$incidence_plot_population_colour
      )
  })
  output$incidence_plot_population <- shiny::renderUI({
    x <- getIncidencePlotPopulation()
    renderInteractivePlot(x, input$incidence_plot_population_interactive)
  })

  # incidence_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$incidence_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$incidence_attrition_cdm_name,
      input$incidence_attrition_outcome_cohort_name,
      input$incidence_attrition_analysis_censor_cohort_name,
      input$incidence_attrition_analysis_complete_database_intervals,
      input$incidence_attrition_analysis_outcome_washout,
      input$incidence_attrition_analysis_repeated_events,
      input$incidence_attrition_denominator_age_group,
      input$incidence_attrition_denominator_days_prior_observation,
      input$incidence_attrition_denominator_end_date,
      input$incidence_attrition_denominator_requirements_at_entry,
      input$incidence_attrition_denominator_sex,
      input$incidence_attrition_denominator_start_date,
      input$incidence_attrition_denominator_target_cohort_name,
      input$incidence_attrition_denominator_time_at_risk,
      input$incidence_attrition_standardised_incidence,
      input$incidence_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$incidence_attrition, {
    if (updateButtons$incidence_attrition == TRUE) {
      output$update_message_incidence_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_incidence_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_incidence_attrition, {
    updateButtons$incidence_attrition <- FALSE
  })

  ## get incidence_attrition data
  getIncidenceAttritionData <- shiny::eventReactive(input$update_incidence_attrition, {
    data[["incidence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_attrition_cdm_name,
        .data$variable_name %in% input$incidence_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$incidence_attrition_outcome_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis_censor_cohort_name %in% input$incidence_attrition_analysis_censor_cohort_name,
        .data$analysis_complete_database_intervals %in% input$incidence_attrition_analysis_complete_database_intervals,
        .data$analysis_outcome_washout %in% input$incidence_attrition_analysis_outcome_washout,
        .data$analysis_repeated_events %in% input$incidence_attrition_analysis_repeated_events,
        .data$denominator_age_group %in% input$incidence_attrition_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$incidence_attrition_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$incidence_attrition_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$incidence_attrition_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$incidence_attrition_denominator_sex,
        .data$denominator_start_date %in% input$incidence_attrition_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$incidence_attrition_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$incidence_attrition_denominator_time_at_risk,
        .data$standardised_incidence %in% input$incidence_attrition_standardised_incidence
      )
  })
  getIncidenceAttritionTable <- shiny::reactive({
    res <- getIncidenceAttritionData()
    res |>
      IncidencePrevalence::tableIncidenceAttrition(
        header = input$incidence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$incidence_attrition_table_group_column,
        hide = input$incidence_attrition_table_hide
      )
  })
  output$incidence_attrition_table <- gt::render_gt({
    getIncidenceAttritionTable()
  })
  output$incidence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence_attrition.", input$incidence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceAttritionTable(), file)
    }
  )

  

  # hr_summary -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$hr_summary <- TRUE
  }) |>
    shiny::bindEvent(
      input$hr_summary_cdm_name,
      input$hr_summary_transition,
      input$hr_summary_ref_age,
      input$hr_summary_model_name,
      input$hr_summary_variable_name,
      input$hr_summary_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$hr_summary, {
    if (updateButtons$hr_summary == TRUE) {
      output$update_message_hr_summary <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_hr_summary <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_hr_summary, {
    updateButtons$hr_summary <- FALSE
  })

  ## get hr_summary data
  getHrSummaryData <- shiny::eventReactive(input$update_hr_summary, {
    data[["hr_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$hr_summary_cdm_name,
        .data$variable_name %in% input$hr_summary_variable_name,
        .data$estimate_name %in% input$hr_summary_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$transition %in% input$hr_summary_transition) |>
      omopgenerics::filterAdditional(.data$model_name %in% input$hr_summary_model_name)
  })
  getHrSummaryAgeModelTable <- shiny::reactive({
    getHrSummaryData() |> 
      omopgenerics::filterStrata(.data$ref_age == "70") |>
      omopgenerics::tidy() |>
      visOmopResults::visTable(type = "reactable", 
                                   hide = "variable_name",
                                   rename = c("Relative age" = "variable_level", "Reference age" = "ref_age")
                                   )
  })
  output$hr_summary_age_model_table <- reactable::renderReactable({
    getHrSummaryAgeModelTable()
  })
  output$hr_summary_age_model_table_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getHrSummaryData() |>
        omopgenerics::filterStrata(.data$ref_age == "70") |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getHrSummaryTable <- shiny::reactive({
    getHrSummaryData() |>
      omopgenerics::filterStrata(.data$ref_age != "70") |>
      simpleTable(
        header = input$hr_summary_table_header,
        group = input$hr_summary_table_group_column,
        hide = input$hr_summary_table_hide
      )
  })
  output$hr_summary_table <- gt::render_gt({
    getHrSummaryTable()
  })
  output$hr_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$hr_summary_table_format),
    content = function(file) {
      gt::gtsave(getHrSummaryTable(), file)
    }
  )
  getHrAgeModelPlot<- shiny::reactive({
    getHrSummaryData() |>
      omopgenerics::filterStrata(.data$ref_age == "70") |>
      omopgenerics::tidy()|>
      dplyr::mutate(rel_age = as.numeric(.data$variable_level) ) |>
      visOmopResults::scatterPlot(x = "rel_age", 
                                  y = "hazard_ratio", 
                                  line = TRUE, 
                                  point = FALSE, 
                                  ribbon = FALSE,
                                  facet =  input$hr_summary_age_model_plot_facet,
                                  colour = input$hr_summary_age_model_plot_colour) +
      geom_line(aes(y = lower_hr), linetype = "dashed", linewidth = 0.6) +
      geom_line(aes(y = upper_hr), linetype = "dashed", linewidth = 0.6) +
      coord_cartesian(ylim = c(0, 10)) +
      labs(
        title = "Relative hazard ratios: age only model",
        subtitle = "Reference age: 70"
      )
  })
  output$hr_summary_age_model_plot <- shiny::renderUI({
    x <- getHrAgeModelPlot()
    renderInteractivePlot(x, input$hr_summary_age_model_plot_interactive)
  })
  output$hr_summary_age_model_plot_download <- shiny::downloadHandler(
    filename = "plot_age_model.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getHrAgeModelPlot(),
        width = as.numeric(input$hr_summary_age_model_plot_width),
        height = as.numeric(input$hr_summary_age_model_plot_height),
        units = input$hr_summary_age_model_units,
        dpi = as.numeric(input$hr_summary_age_model_plot_dpi)
      )
    }
  )
  
  getHrPlot<- shiny::reactive({
    getHrSummaryData() |>
      omopgenerics::filterStrata(.data$ref_age != "70") |>
      dplyr::filter(variable_name != "age") |>
      visOmopResults::scatterPlot(x = "variable_level", 
                                  y = "hazard_ratio", 
                                  line = FALSE, 
                                  point = TRUE, 
                                  ribbon = FALSE,
                                  facet = input$hr_summary_plot_facet, 
                                  colour =input$hr_summary_plot_colour,
                                  ymin = "lower_hr", 
                                  ymax = "upper_hr") +
      geom_hline(yintercept = 1, linetype = "dashed", linewidth = 0.6, color = "black") +
      coord_cartesian(ylim = c(0,3)) 

  })
  output$hr_summary_plot <- shiny::renderUI({
    x <- getHrPlot()
    renderInteractivePlot(x, input$hr_summary_plot_interactive)
  })
  output$hr_summary_plot_download <- shiny::downloadHandler(
    filename = "plot_hr_multi_state_model.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getHrPlot(),
        width = as.numeric(input$hr_summary_plot_width),
        height = as.numeric(input$hr_summary_plot_height),
        units = input$hr_summary_units,
        dpi = as.numeric(input$hr_summary_plot_dpi)
      )
    }
  )
}
