# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    orphan_code_use = FALSE,
    cohort_code_use = FALSE
  )


  # orphan_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$orphan_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$orphan_code_use_cdm_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$orphan_code_use, {
    if (updateButtons$orphan_code_use == TRUE) {
      output$update_message_orphan_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_orphan_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_orphan_code_use, {
    updateButtons$orphan_code_use <- FALSE
  })

  ## get orphan_code_use data
  getOrphanCodeUseData <- shiny::eventReactive(input$update_orphan_code_use, {
    t <- data[["orphan_code_use"]] |>
      dplyr::filter(.data$cdm_name %in% input$orphan_code_use_cdm_name) |>
      dplyr::filter(.data$variable_level %in% input$orphan_code_use_variable_level) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$orphan_code_use_omop_table)
    
    if(isTRUE(input$orphan_code_use_type)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts_standard")
    }
    
  })
  getOrphanCodeUseTableReact <- shiny::reactive({
    getOrphanCodeUseData()  |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id",
                              "Codelist" = "variable_level"),
                   hide = c("variable_name", "type", "estimate_name", "relationship_id"), 
                   header = "cdm_name", 
                   columnOrder = c("variable_level")) 
  })
  output$orphan_code_use_table_react <- reactable::renderReactable({
    getOrphanCodeUseTableReact()
  })
  getOrphanCodeUseTableGt <- shiny::reactive({
    getOrphanCodeUseData() |>
      CodelistGenerator::tableOrphanCodes(
        header = input$orphan_code_use_table_gt_header,
        groupColumn = input$orphan_code_use_table_gt_group_column,
        hide = input$orphan_code_use_table_gt_hide
      )
  })
  output$orphan_code_use_table_gt <- gt::render_gt({
    getOrphanCodeUseTableGt()
  })
  output$orphan_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_orphan_codes.", input$orphan_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getOrphanCodeUseTableGt(), file)
    }
  )

  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_omop_table,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    t <- data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_level %in% input$cohort_code_use_variable_level
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$cohort_code_use_omop_table) 
    
    if(isTRUE(input$cohort_code_use_type)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use_standard")
    }
    
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id",
                              "Codelist" = "variable_level"),
                   hide = c("variable_name", "type", "estimate_name"), 
                   header = "cdm_name", 
                   columnOrder = c("variable_level")) 
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )
}
