# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    orphan_code_use_cci = FALSE,
    cohort_code_use_cci = FALSE,
    orphan_code_use_efi = FALSE,
    cohort_code_use_efi = FALSE
  )

  # orphan_code_use_efi -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$orphan_code_use_efi <- TRUE
  }) |>
    shiny::bindEvent(
      input$orphan_code_use_cdm_name_efi,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$orphan_code_use_efi, {
    if (updateButtons$orphan_code_use_efi == TRUE) {
      output$update_message_orphan_code_use_efi <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_orphan_code_use_efi <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_orphan_code_use_efi, {
    updateButtons$orphan_code_use_efi <- FALSE
  })
  
  ## get orphan_code_use data
  getOrphanCodeUseDataEFI <- shiny::eventReactive(input$update_orphan_code_use_efi, {
    t <- data[["orphan_code_use"]] |>
      dplyr::filter(.data$cdm_name %in% input$orphan_code_use_cdm_name_efi) |>
      dplyr::filter(.data$variable_level %in% input$orphan_code_use_variable_level_efi) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$orphan_code_use_omop_table_efi,
                                .data$index %in% "efi") 
    
    if(isTRUE(input$orphan_code_use_type_efi)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts_standard")
    }
    
  })
  getOrphanCodeUseTableReactEFI <- shiny::reactive({
    getOrphanCodeUseDataEFI()  |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id"),
                   hide = c("variable_name", "type", "estimate_name", "relationship_id", "cohort_name"), 
                   header = "cdm_name", 
                   groupColumn = "variable_level", 
                   columnOrder = c("variable_level")) 
  })
  output$orphan_code_use_table_react_efi <- reactable::renderReactable({
    getOrphanCodeUseTableReactEFI()
  })
  
  # orphan_code_use_cci -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$orphan_code_use_cci <- TRUE
  }) |>
    shiny::bindEvent(
      input$orphan_code_use_cdm_name_cci,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$orphan_code_use_cci, {
    if (updateButtons$orphan_code_use_cci == TRUE) {
      output$update_message_orphan_code_use_cci <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_orphan_code_use_cci <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_orphan_code_use_cci, {
    updateButtons$orphan_code_use_cci <- FALSE
  })

  ## get orphan_code_use data
  getOrphanCodeUseDataCCI <- shiny::eventReactive(input$update_orphan_code_use_cci, {
    t <- data[["orphan_code_use"]] |>
      dplyr::filter(.data$cdm_name %in% input$orphan_code_use_cdm_name_cci) |>
      dplyr::filter(.data$variable_level %in% input$orphan_code_use_variable_level_cci) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$orphan_code_use_omop_table_cci,
                                .data$index %in% "cci") 

    if(isTRUE(input$orphan_code_use_type_cci)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "orphan_code_counts_standard")
    }
    
  })
  getOrphanCodeUseTableReactCCI <- shiny::reactive({
    getOrphanCodeUseDataCCI()  |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id"),
                   hide = c("variable_name", "type", "estimate_name", "relationship_id", "cohort_name"), 
                   header = "cdm_name", 
                   groupColumn = "variable_level", 
                   columnOrder = c("variable_level")) 
  })
  output$orphan_code_use_table_react_cci <- reactable::renderReactable({
    getOrphanCodeUseTableReactCCI()
  })

  # cohort_code_use_cci -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use_cci <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name_cci,
      input$cohort_code_use_omop_table_cci,
      input$cohort_code_use_variable_name_cci,
      input$cohort_code_use_estimate_name_cci,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use_cci, {
    if (updateButtons$cohort_code_use_cci == TRUE) {
      output$update_message_cohort_code_use_cci <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_cohort_code_use_cci <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use_cci, {
    updateButtons$cohort_code_use_cci <- FALSE
  })

  ## get cohort_code_use data_cci
  getCohortCodeUseDataCCI <- shiny::eventReactive(input$update_cohort_code_use_cci, {
    t <- data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name_cci,
        .data$variable_level %in% input$cohort_code_use_variable_level_cci,
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$cohort_code_use_omop_table_cci,
                                .data$index %in% "cci") 
    
    if(isTRUE(input$cohort_code_use_type_cci)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use_standard")
    }
    
  })
  getCohortCodeUseTableReactCCI <- shiny::reactive({
    getCohortCodeUseDataCCI() |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id",
                              "Cohort name" = "variable_level"),
                   hide = c("variable_name", "type", "estimate_name", "cohort_name", "efi"), 
                   header = "cdm_name", groupColumn = "codelist_name",
                   columnOrder = c("variable_level")) 
  })
  output$cohort_code_use_table_react_cci <- reactable::renderReactable({
    getCohortCodeUseTableReactCCI()
  })
  
  # -----
  # cohort_code_use_efi -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use_efi <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name_efi,
      input$cohort_code_use_omop_table_efi,
      input$cohort_code_use_variable_name_efi,
      input$cohort_code_use_estimate_name_efi,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use_efi, {
    if (updateButtons$cohort_code_use_efi == TRUE) {
      output$update_message_cohort_code_use_efi <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_cohort_code_use_efi <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use_efi, {
    updateButtons$cohort_code_use_efi <- FALSE
  })
  
  ## get cohort_code_use data_efi
  getCohortCodeUseDataEFI <- shiny::eventReactive(input$update_cohort_code_use_efi, {
    t <- data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name_efi,
        .data$variable_level %in% input$cohort_code_use_variable_level_efi,
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$cohort_code_use_omop_table_efi,
                                .data$index %in% "efi") 
    
    if(isTRUE(input$cohort_code_use_type_efi)) {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use")
    } else {
      t |>
        omopgenerics::filterAdditional(.data$type %in% "cohort_code_use_standard")
    }
    
  })
  getCohortCodeUseTableReactEFI <- shiny::reactive({
    getCohortCodeUseDataEFI() |>
      visOmopTable(type = "reactable",
                   rename = c("Standard Concept Name" = "concept_name",
                              "Standard Concept ID" = "concept_id",
                              "Cohort name" = "variable_level"),
                   hide = c("variable_name", "type", "estimate_name", "cohort_name", "efi"), 
                   header = "cdm_name", groupColumn = "codelist_name",
                   columnOrder = c("variable_level")) 
  })
  output$cohort_code_use_table_react_efi <- reactable::renderReactable({
    getCohortCodeUseTableReactEFI()
  })
  
  # -----
  
}
