# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_menu(
    title = "Charlson Comorbidity Index",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Orphan codes",
      icon = shiny::icon("magnifying-glass-arrow-right"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_orphan_code_use_cci",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_orphan_code_use_cci")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_cdm_name_cci",
            label = "CDM name",
            choices = choices$orphan_code_use_cdm_name_cci,
            selected = selected$orphan_code_use_cdm_name_cci,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_variable_level_cci",
            label = "Cohort name",
            choices = choices$orphan_code_use_variable_level_cci,
            selected = selected$orphan_code_use_variable_level_cci,
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_omop_table_cci",
            label = "OMOP table",
            choices = choices$orphan_code_use_omop_table_cci,
            selected = selected$orphan_code_use_omop_table_cci,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::prettySwitch(
            inputId = "orphan_code_use_type_cci",
            label = "Show source codes"
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Orphan codes (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("orphan_code_use_table_react_cci") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_cohort_code_use_cci",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_cohort_code_use_cci")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name_cci",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name_cci,
            selected = selected$cohort_code_use_cdm_name_cci,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_variable_level_cci",
            label = "Cohort name",
            choices = choices$cohort_code_use_variable_level_cci,
            selected = selected$cohort_code_use_variable_level_cci,
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_omop_table_cci",
            label = "OMOP table",
            choices = choices$cohort_code_use_omop_table_cci,
            selected = selected$cohort_code_use_omop_table_cci,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::prettySwitch(
            inputId = "cohort_code_use_type_cci",
            label = "Show source codes"
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react_cci") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Electronic Frailty Index",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Orphan codes",
      icon = shiny::icon("magnifying-glass-arrow-right"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_orphan_code_use_efi",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_orphan_code_use_efi")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_cdm_name_efi",
            label = "CDM name",
            choices = choices$orphan_code_use_cdm_name_efi,
            selected = selected$orphan_code_use_cdm_name_efi,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_variable_level_efi",
            label = "Cohort name",
            choices = choices$orphan_code_use_variable_level_efi,
            selected = selected$orphan_code_use_variable_level_efi,
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "orphan_code_use_omop_table_efi",
            label = "OMOP table",
            choices = choices$orphan_code_use_omop_table_efi,
            selected = selected$orphan_code_use_omop_table_efi,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::prettySwitch(
            inputId = "orphan_code_use_type_efi",
            label = "Show source codes"
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Orphan codes (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("orphan_code_use_table_react_efi") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_cohort_code_use_efi",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_cohort_code_use_efi")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name_efi",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name_efi,
            selected = selected$cohort_code_use_cdm_name_efi,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_variable_level_efi",
            label = "Cohort name",
            choices = choices$cohort_code_use_variable_level_efi,
            selected = selected$cohort_code_use_variable_level_efi,
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_omop_table_efi",
            label = "OMOP table",
            choices = choices$cohort_code_use_omop_table_efi,
            selected = selected$cohort_code_use_omop_table_efi,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::prettySwitch(
            inputId = "cohort_code_use_type_efi",
            label = "Show source codes"
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react_efi") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
